### ISSUE TITLE
button in web interface sends request to `localhost` instead of document url

### ISSUE THREAD

**Issue by moleus** [ad/domru#11]
HostIp in rendered html document is `localhost` when running in docker container. Therefore "Открыть" button doesn't work. 
Maybe we should use `document.URL` in js to construct the url. 

https://github.com/ad/domru/blob/1b093ba59c1b39aab6430345288a0684b68ee050/templates/home.html#L96
![image](https://github.com/ad/domru/assets/66182149/d10c08ae-da8f-47ea-ba7e-f1a44c8e586a)
![image](https://github.com/ad/domru/assets/66182149/6768ca1f-deba-4d64-943c-a028a22963f1)

**Comment by ad** [comment]
The problem is here https://github.com/ad/domru/blob/1b093ba59c1b39aab6430345288a0684b68ee050/handlers/auth.go#L186-L190

you don't have host ip, maybe you run code not from homeassistant addon

at that moment I don't have domofon for test :(

**Comment by Moleus** [comment]
U are right, I'm running application in a standalone docker container, not as the HA addon.

Thank you for the code reference. I'll have a look at this and test in a few weeks
