### ISSUE TITLE
Implementation of the hash function. 

### ISSUE THREAD

**Issue by Moleus** [ad/domru#2]
I've seen your [comment](https://github.com/alexmorbo/domru/issues/1#issuecomment-772035360) and I'd like to share the implementation of 2 hash functions which were used to encrypt password (hash1) and login+timestamp+password (hash2). 

I've checked it using my own credentials and this implementation gave correct results. 

This code is decompiled from the apk and slightly simplified to be more readable.
[A link to the gist](https://gist.github.com/Moleus/0ba672fc9b880be1f68d174a96334fc0) 

I don't know much about Go, but hope that this will help

**Comment by ad** [comment]
Good job :)
But we have already changed the authorization process to the same as in the application (with sms code)
