### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by sergey144010** [ad/domru#3]
В описании

```
docker run --name domru --rm -p 8080:18000 DOMRU_LOGIN=1234567890 -e DOMRU_TOKEN=qwerty -e DOMRU_REFRESH=qwerty -e DOMRU_OPERATOR=2 -e DOMRU_PORT=18000 ad/domru:latest
```
не хватает -e перед
DOMRU_LOGIN=1234567890

И вопрос: если есть номер договора (скорее всего это логин) и пароль, каким образом залогиниться?

**Comment by ad** [comment]
Спасибо, поправил.

По идее, должно хватить:
`docker run --name domru --rm -p 8080:18000 -e DOMRU_PORT=18000 ad/domru:latest`

а потом открыть [http://localhost:8080/login](http://localhost:8080/login)

и пройти авторизацию, в результате будет создан `/share/domofon/account.json` (путь прибит в коде, в принципе, можно сделать, чтобы из переменных окружения брал)  с нужными для дальнейшей работы данными (их можно передать через переменные окружения или пусть само из файла берет/обновляет).

**Comment by sergey144010** [comment]
Имею приложение - Умный дом.ру
Вхожу туда по:
Договор: 3600... - длина 12 цифр
Пароль: длина 8 цифр

Запускаю контейнер:
```bash
docker run --name domru --rm -p 8080:18000 -e DOMRU_LOGIN=договор -e DOMRU_TOKEN=пароль -e DOMRU_PORT=18000 ad/domru:latest
```

в консоли:
```
2022/09/26 15:26:36 config: &{Token:пароль RefreshToken: Login:договор Operator:0 Port:18000 UseWebsocket:false}
2022/09/26 15:26:36 start listening on 18000 with token пароль
```
захожу на http://localhost:8080/login
жму - Войти по номеру телефона

в консоли
```
2022/09/26 15:29:49 login error: Get "https://myhome.novotelecom.ru/auth/v2/login/договор": net/http: TLS handshake timeout
```

Оно же не только с homeAssistant должно работать? Апи на геолокации не завязано, разные города один апи? Формат файла accounts.json, что конкретно внутри должно быть? Апи дом.ру есть открытом доступе, можно его где-то посмотреть?

**Comment by ad** [comment]
Обновил ридми:

`docker build -t ad/domru:latest .`

`docker run --name domru --rm -p 8080:18000 -e DOMRU_PORT=18000 -v $(pwd)/accounts.json:/share/domofon/account.json ad/domru:latest`

открыть в браузере http://localhost:8080/login

ввести номер телефона в формате 79xxxxxxxxx
выбрать адрес
придет смс, ввести код из смс
если всё верно, то напишет токен и рефреш токен, а также сохранит всё что нужно для работы в accounts.json

перезапустить контейнер, чтобы проверить что все работает

`docker run --name domru --rm -p 8080:18000 -e DOMRU_PORT=18000 -v $(pwd)/accounts.json:/share/domofon/account.json ad/domru:latest`

открыть http://localhost:8080

**Comment by sergey144010** [comment]
понятно, спасибо, т.е. получается всё-таки нужен номер телефона. Мобильное приложение пускает по номеру договора и паролю, видимо есть еще апи, где бы на него посмотреть.

**Comment by h1opok** [comment]
Подскажите я ещё учусь конечно 📑 но у меня заблокировали мой домофон. 
код пароль заблокировали и за не уплату. 
мы живем с отцом и не когда не платили за дверь деньги. 
Они не имеют права ограничивать вход в жильё это уголовная ответственность. 
Дайте мне ключ 🔐 пожалуйста ☺️
